//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnSpy.Debugger.DotNet.CorDebug.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class dnSpy_Debugger_DotNet_CorDebug_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal dnSpy_Debugger_DotNet_CorDebug_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dnSpy.Debugger.DotNet.CorDebug.Properties.dnSpy.Debugger.DotNet.CorDebug.Resource" +
                            "s", typeof(dnSpy_Debugger_DotNet_CorDebug_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_rguments.
        /// </summary>
        public static string DbgAsm_Args {
            get {
                return ResourceManager.GetString("DbgAsm_Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Break at.
        /// </summary>
        public static string DbgAsm_BreakAt {
            get {
                return ResourceManager.GetString("DbgAsm_BreakAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xecutable.
        /// </summary>
        public static string DbgAsm_Executable {
            get {
                return ResourceManager.GetString("DbgAsm_Executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Host.
        /// </summary>
        public static string DbgAsm_Host {
            get {
                return ResourceManager.GetString("DbgAsm_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Ar_guments.
        /// </summary>
        public static string DbgAsm_HostArgs {
            get {
                return ResourceManager.GetString("DbgAsm_HostArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use host executable.
        /// </summary>
        public static string DbgAsm_UseHostExecutable {
            get {
                return ResourceManager.GetString("DbgAsm_UseHostExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Working Directory.
        /// </summary>
        public static string DbgAsm_WorkingDir {
            get {
                return ResourceManager.GetString("DbgAsm_WorkingDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateProcess.
        /// </summary>
        public static string DbgBreak_CreateProcessEvent {
            get {
                return ResourceManager.GetString("DbgBreak_CreateProcessEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Break.
        /// </summary>
        public static string DbgBreak_Dont {
            get {
                return ResourceManager.GetString("DbgBreak_Dont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Point.
        /// </summary>
        public static string DbgBreak_EntryPoint {
            get {
                return ResourceManager.GetString("DbgBreak_EntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A CLR debugger error occurred. Terminate the debugged process and try again.
        ///
        ///HR: 0x{0:X8}
        ///Error: 0x{1:X8}.
        /// </summary>
        public static string Error_CLRDebuggerErrorOccurred {
            get {
                return ResourceManager.GetString("Error_CLRDebuggerErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not attach to process {0}.
        /// </summary>
        public static string Error_CouldNotAttachToProcess {
            get {
                return ResourceManager.GetString("Error_CouldNotAttachToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not break process. Error: 0x{0:X8}.
        /// </summary>
        public static string Error_CouldNotBreakProcess {
            get {
                return ResourceManager.GetString("Error_CouldNotBreakProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find .NET Core host &apos;{0}&apos;.
        /// </summary>
        public static string Error_CouldNotFindDotNetCoreHost {
            get {
                return ResourceManager.GetString("Error_CouldNotFindDotNetCoreHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set the next statement..
        /// </summary>
        public static string Error_CouldNotSetNextStatement {
            get {
                return ResourceManager.GetString("Error_CouldNotSetNextStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start the debugger. {0}.
        /// </summary>
        public static string Error_CouldNotStartDebugger {
            get {
                return ResourceManager.GetString("Error_CouldNotStartDebugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start debugger.
        ///
        ///Error: {0}.
        /// </summary>
        public static string Error_CouldNotStartDebugger2 {
            get {
                return ResourceManager.GetString("Error_CouldNotStartDebugger2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start the debugger. Make sure you have access to the file &apos;{0}&apos;
        ///
        ///Error: {1}.
        /// </summary>
        public static string Error_CouldNotStartDebuggerCheckAccessToFile {
            get {
                return ResourceManager.GetString("Error_CouldNotStartDebuggerCheckAccessToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start the debugger. The debugged program requires admin privileges. Restart dnSpy with admin rights and try again..
        /// </summary>
        public static string Error_CouldNotStartDebuggerRequireAdminPrivLvl {
            get {
                return ResourceManager.GetString("Error_CouldNotStartDebuggerRequireAdminPrivLvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file doesn&apos;t exist.
        /// </summary>
        public static string Error_FileDoesNotExist {
            get {
                return ResourceManager.GetString("Error_FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing filename.
        /// </summary>
        public static string Error_MissingFilename {
            get {
                return ResourceManager.GetString("Error_MissingFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some other process is already debugging process {0}.
        /// </summary>
        public static string Error_ProcessIsAlreadyBeingDebugged {
            get {
                return ResourceManager.GetString("Error_ProcessIsAlreadyBeingDebugged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&lt;no exception message&gt;&quot;.
        /// </summary>
        public static string ExceptionMessageIsNull {
            get {
                return ResourceManager.GetString("ExceptionMessageIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IL offset {0}.
        /// </summary>
        public static string GlyphToolTip_IL_offset_0 {
            get {
                return ResourceManager.GetString("GlyphToolTip_IL_offset_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line {0} character {1}.
        /// </summary>
        public static string GlyphToolTip_line_0_character_1 {
            get {
                return ResourceManager.GetString("GlyphToolTip_line_0_character_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address {0}.
        /// </summary>
        public static string GlyphToolTip_NativeAddress {
            get {
                return ResourceManager.GetString("GlyphToolTip_NativeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal debugger error.
        /// </summary>
        public static string InternalDebuggerError {
            get {
                return ResourceManager.GetString("InternalDebuggerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugger ({0}).
        /// </summary>
        public static string Plugin_ShortDescription {
            get {
                return ResourceManager.GetString("Plugin_ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appdomain Transition.
        /// </summary>
        public static string StackFrame_AppdomainTransition {
            get {
                return ResourceManager.GetString("StackFrame_AppdomainTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Init.
        /// </summary>
        public static string StackFrame_ClassInit {
            get {
                return ResourceManager.GetString("StackFrame_ClassInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string StackFrame_Exception {
            get {
                return ResourceManager.GetString("StackFrame_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Evaluation.
        /// </summary>
        public static string StackFrame_FunctionEvaluation {
            get {
                return ResourceManager.GetString("StackFrame_FunctionEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Call.
        /// </summary>
        public static string StackFrame_InternalCall {
            get {
                return ResourceManager.GetString("StackFrame_InternalCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Frame ({0}).
        /// </summary>
        public static string StackFrame_InternalFrame {
            get {
                return ResourceManager.GetString("StackFrame_InternalFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JIT Compilation.
        /// </summary>
        public static string StackFrame_JITCompilation {
            get {
                return ResourceManager.GetString("StackFrame_JITCompilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightweight Function.
        /// </summary>
        public static string StackFrame_LightweightFunction {
            get {
                return ResourceManager.GetString("StackFrame_LightweightFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed to Native Transition.
        /// </summary>
        public static string StackFrame_ManagedToNativeTransition {
            get {
                return ResourceManager.GetString("StackFrame_ManagedToNativeTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native Frame {0}.
        /// </summary>
        public static string StackFrame_NativeFrame {
            get {
                return ResourceManager.GetString("StackFrame_NativeFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native to Managed Transition.
        /// </summary>
        public static string StackFrame_NativeToManagedTransition {
            get {
                return ResourceManager.GetString("StackFrame_NativeToManagedTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string StackFrame_Security {
            get {
                return ResourceManager.GetString("StackFrame_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Thread_UserState_Background {
            get {
                return ResourceManager.GetString("Thread_UserState_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string Thread_UserState_Stopped {
            get {
                return ResourceManager.GetString("Thread_UserState_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StopRequested.
        /// </summary>
        public static string Thread_UserState_StopRequested {
            get {
                return ResourceManager.GetString("Thread_UserState_StopRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        public static string Thread_UserState_Suspended {
            get {
                return ResourceManager.GetString("Thread_UserState_Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuspendRequested.
        /// </summary>
        public static string Thread_UserState_SuspendRequested {
            get {
                return ResourceManager.GetString("Thread_UserState_SuspendRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThreadPool.
        /// </summary>
        public static string Thread_UserState_ThreadPool {
            get {
                return ResourceManager.GetString("Thread_UserState_ThreadPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnsafePoint.
        /// </summary>
        public static string Thread_UserState_UnsafePoint {
            get {
                return ResourceManager.GetString("Thread_UserState_UnsafePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unstarted.
        /// </summary>
        public static string Thread_UserState_Unstarted {
            get {
                return ResourceManager.GetString("Thread_UserState_Unstarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitSleepJoin.
        /// </summary>
        public static string Thread_UserState_WaitSleepJoin {
            get {
                return ResourceManager.GetString("Thread_UserState_WaitSleepJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 32-bit dnSpy to debug 32-bit applications..
        /// </summary>
        public static string UseDnSpy64ExeToDebug32 {
            get {
                return ResourceManager.GetString("UseDnSpy64ExeToDebug32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 64-bit dnSpy to debug 64-bit applications..
        /// </summary>
        public static string UseDnSpyExeToDebug64 {
            get {
                return ResourceManager.GetString("UseDnSpyExeToDebug64", resourceCulture);
            }
        }
    }
}
