/*
    Copyright (C) 2014-2017 de4dot@gmail.com

    This file is part of dnSpy

    dnSpy is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    dnSpy is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with dnSpy.  If not, see <http://www.gnu.org/licenses/>.
*/

using System.Collections.Generic;
using dnSpy.Contracts.Debugger.Exceptions;

namespace dnSpy.Debugger.CorDebug.Common {
	[ExportDbgExceptionDefinitionProvider]
	sealed class DotNetDbgExceptionDefinitionProvider : DbgExceptionDefinitionProvider {
		// See ExceptionInfo.cs on how to regenerate this array
		static readonly ExceptionInfo[] exceptionInfos = new ExceptionInfo[] {
			new ExceptionInfo("Microsoft.JScript.JScriptException", DbgExceptionDefinitionFlags.None),
			new ExceptionInfo("System.AccessViolationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.AggregateException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.AppDomainUnloadedException", DbgExceptionDefinitionFlags.None),
			new ExceptionInfo("System.ApplicationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ArgumentException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ArgumentNullException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ArgumentOutOfRangeException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ArithmeticException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ArrayTypeMismatchException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.BadImageFormatException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.CannotUnloadAppDomainException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Collections.Generic.KeyNotFoundException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ComponentModel.Composition.ChangeRejectedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ComponentModel.Composition.CompositionContractMismatchException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ComponentModel.Composition.CompositionException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ComponentModel.Composition.ImportCardinalityMismatchException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ComponentModel.Composition.Primitives.ComposablePartException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ComponentModel.DataAnnotations.ValidationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ComponentModel.Design.CheckoutException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ComponentModel.Design.ExceptionCollection", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ComponentModel.Design.Serialization.CodeDomSerializerException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ComponentModel.InvalidEnumArgumentException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ComponentModel.LicenseException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ComponentModel.WarningException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ComponentModel.Win32Exception", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Configuration.ConfigurationErrorsException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Configuration.ConfigurationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Configuration.Install.InstallException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Configuration.Provider.ProviderException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Configuration.SettingsPropertyCannotBeSetForAnonymousUserException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Configuration.SettingsPropertyIsReadOnlyException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Configuration.SettingsPropertyNotFoundException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Configuration.SettingsPropertyWrongTypeException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ContextMarshalException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.Common.DbException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.ConstraintException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.DataException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.DBConcurrencyException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.DeletedRowInaccessibleException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.DuplicateNameException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.EvaluateException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.InRowChangingEventException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.InvalidConstraintException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.InvalidExpressionException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.Linq.ChangeConflictException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.Linq.DuplicateKeyException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.MissingPrimaryKeyException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.NoNullAllowedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.Odbc.OdbcException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.OleDb.OleDbException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.OperationAbortedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.OracleClient.OracleException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.ReadOnlyException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.RowNotInTableException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.SqlClient.SqlException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.SqlTypes.SqlException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.SqlTypes.SqlNotFilledException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.SqlTypes.SqlNullValueException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.SqlTypes.SqlTruncateException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.SqlTypes.SqlTypeException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.StrongTypingException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.SyntaxErrorException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.TypedDataSetGeneratorException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Data.VersionNotFoundException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DataMisalignedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Deployment.Application.DependentPlatformMissingException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Deployment.Application.DeploymentDownloadException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Deployment.Application.DeploymentException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Deployment.Application.InvalidDeploymentException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Deployment.Application.TrustNotGrantedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Diagnostics.Eventing.Reader.EventLogException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Diagnostics.Eventing.Reader.EventLogInvalidDataException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Diagnostics.Eventing.Reader.EventLogNotFoundException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Diagnostics.Eventing.Reader.EventLogProviderDisabledException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Diagnostics.Eventing.Reader.EventLogReadingException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DirectoryServices.AccountManagement.MultipleMatchesException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DirectoryServices.AccountManagement.NoMatchingPrincipalException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DirectoryServices.AccountManagement.PasswordException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DirectoryServices.AccountManagement.PrincipalException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DirectoryServices.AccountManagement.PrincipalExistsException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DirectoryServices.AccountManagement.PrincipalOperationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DirectoryServices.AccountManagement.PrincipalServerDownException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectExistsException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DirectoryServices.ActiveDirectory.ActiveDirectoryOperationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DirectoryServices.ActiveDirectory.ActiveDirectoryServerDownException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DirectoryServices.ActiveDirectory.ForestTrustCollisionException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DirectoryServices.ActiveDirectory.SyncFromAllServersOperationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DirectoryServices.DirectoryServicesCOMException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DirectoryServices.Protocols.BerConversionException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DirectoryServices.Protocols.DirectoryException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DirectoryServices.Protocols.DirectoryOperationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DirectoryServices.Protocols.DsmlInvalidDocumentException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DirectoryServices.Protocols.ErrorResponseException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DirectoryServices.Protocols.LdapException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DirectoryServices.Protocols.TlsOperationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DivideByZeroException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DllNotFoundException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Drawing.Printing.InvalidPrinterException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.DuplicateWaitObjectException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.EnterpriseServices.RegistrationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.EnterpriseServices.ServicedComponentException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.EntryPointNotFoundException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Exception", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ExecutionEngineException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.FieldAccessException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.FormatException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IdentityModel.Selectors.CardSpaceException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IdentityModel.Selectors.IdentityValidationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IdentityModel.Selectors.PolicyValidationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IdentityModel.Selectors.ServiceBusyException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IdentityModel.Selectors.ServiceNotStartedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IdentityModel.Selectors.StsCommunicationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IdentityModel.Selectors.UnsupportedPolicyOptionsException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IdentityModel.Selectors.UntrustedRecipientException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IdentityModel.Selectors.UserCancellationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IdentityModel.Tokens.SecurityTokenException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IdentityModel.Tokens.SecurityTokenValidationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IndexOutOfRangeException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.InsufficientMemoryException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.InvalidCastException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.InvalidOperationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.InvalidProgramException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.InvalidTimeZoneException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IO.DirectoryNotFoundException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IO.DriveNotFoundException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IO.EndOfStreamException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IO.FileFormatException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IO.FileLoadException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IO.FileNotFoundException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IO.InternalBufferOverflowException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IO.InvalidDataException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IO.IOException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IO.IsolatedStorage.IsolatedStorageException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IO.Log.ReservationNotFoundException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IO.Log.SequenceFullException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IO.PathTooLongException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.IO.PipeException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.ActionPreferenceStopException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.ApplicationFailedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.ArgumentTransformationMetadataException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.CmdletInvocationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.CmdletProviderInvocationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.CommandNotFoundException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.DriveNotFoundException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.ExtendedTypeSystemException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.GetValueException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.GetValueInvocationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.HaltCommandException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.Host.HostException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.Host.PromptingException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.IncompleteParseException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.ItemNotFoundException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.MetadataException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.MethodException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.MethodInvocationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.ParameterBindingException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.ParentContainsErrorRecordException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.ParseException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.ParsingMetadataException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.PipelineClosedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.PipelineStoppedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.ProviderInvocationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.ProviderNameAmbiguousException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.ProviderNotFoundException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.PSArgumentException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.PSArgumentNullException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.PSArgumentOutOfRangeException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.PSInvalidCastException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.PSInvalidOperationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.PSNotImplementedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.PSNotSupportedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.PSObjectDisposedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.PSSecurityException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.RedirectedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.RemoteException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.Runspaces.InvalidPipelineStateException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.Runspaces.InvalidRunspaceStateException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.Runspaces.PSConsoleLoadException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.Runspaces.PSSnapInException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.Runspaces.RunspaceConfigurationAttributeException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.Runspaces.RunspaceConfigurationTypeException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.RuntimeException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.ScriptCallDepthException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.ScriptRequiresException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.SessionStateException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.SessionStateOverflowException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.SessionStateUnauthorizedAccessException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.SetValueException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.SetValueInvocationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.ValidationMetadataException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Automation.WildcardPatternException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.InstanceNotFoundException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.Instrumentation.WmiProviderInstallationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.InstrumentationBaseException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.InstrumentationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Management.ManagementException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.MemberAccessException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Messaging.MessageQueueException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.MethodAccessException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.MissingFieldException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.MissingMemberException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.MissingMethodException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.MulticastNotSupportedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Net.CookieException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Net.HttpListenerException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Net.Mail.SmtpException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Net.Mail.SmtpFailedRecipientException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Net.Mail.SmtpFailedRecipientsException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Net.NetworkInformation.NetworkInformationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Net.NetworkInformation.PingException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Net.PeerToPeer.PeerToPeerException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Net.ProtocolViolationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Net.Sockets.SocketException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Net.WebException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.NotCancelableException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.NotFiniteNumberException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.NotImplementedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.NotSupportedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.NullReferenceException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ObjectDisposedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.OperationCanceledException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.OutOfMemoryException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.OverflowException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.PlatformNotSupportedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Printing.PrintCommitAttributesException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Printing.PrintingCanceledException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Printing.PrintJobException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Printing.PrintQueueException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Printing.PrintServerException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Printing.PrintSystemException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.RankException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Reflection.AmbiguousMatchException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Reflection.InvalidFilterCriteriaException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Reflection.MissingMetadataException", DbgExceptionDefinitionFlags.StopFirstChance | DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Reflection.MissingRuntimeArtifactException", DbgExceptionDefinitionFlags.StopFirstChance | DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Reflection.ReflectionTypeLoadException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Reflection.TargetException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Reflection.TargetInvocationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Reflection.TargetParameterCountException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Resources.MissingManifestResourceException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Resources.MissingSatelliteAssemblyException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Runtime.InteropServices.COMException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Runtime.InteropServices.ComObjectInUseException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Runtime.InteropServices.ExternalException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Runtime.InteropServices.InvalidComObjectException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Runtime.InteropServices.InvalidOleVariantTypeException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Runtime.InteropServices.MarshalDirectiveException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Runtime.InteropServices.SafeArrayRankMismatchException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Runtime.InteropServices.SafeArrayTypeMismatchException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Runtime.InteropServices.SEHException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Runtime.Remoting.MetadataServices.SUDSGeneratorException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Runtime.Remoting.MetadataServices.SUDSParserException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Runtime.Remoting.RemotingException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Runtime.Remoting.RemotingTimeoutException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Runtime.Remoting.ServerException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Runtime.Serialization.InvalidDataContractException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Runtime.Serialization.SerializationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Security.AccessControl.PrivilegeNotHeldException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Security.Authentication.AuthenticationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Security.Authentication.InvalidCredentialException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Security.Cryptography.CryptographicException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Security.Cryptography.CryptographicUnexpectedOperationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Security.HostProtectionException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Security.Policy.PolicyException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Security.Principal.IdentityNotMappedExceptionn", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Security.RightsManagement.RightsManagementException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Security.SecurityException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Security.VerificationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Security.XmlSyntaxException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.ActionNotSupportedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.AddressAccessDeniedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.AddressAlreadyInUseException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.Channels.InvalidChannelBindingException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.Channels.PnrpPeerResolver+PnrpException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.ChannelTerminatedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.CommunicationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.CommunicationObjectAbortedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.CommunicationObjectFaultedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.Dispatcher.FilterInvalidBodyAccessException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.Dispatcher.InvalidBodyAccessException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.Dispatcher.MessageFilterException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.Dispatcher.MultipleFilterMatchesException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.Dispatcher.NavigatorInvalidBodyAccessException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.Dispatcher.XPathNavigatorException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.EndpointNotFoundException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.FaultException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.FaultException`1", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.InvalidMessageContractException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.MessageHeaderException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.MsmqException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.MsmqPoisonMessageException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.PoisonMessageException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.ProtocolException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.QuotaExceededException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.Security.ExpiredSecurityTokenException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.Security.MessageSecurityException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.Security.SecurityAccessDeniedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.Security.SecurityNegotiationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.ServerTooBusyException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceModel.ServiceActivationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.ServiceProcess.TimeoutException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.StackOverflowException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.SystemException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Text.DecoderFallbackException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Text.EncoderFallbackException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Threading.AbandonedMutexException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Threading.LockRecursionException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Threading.SemaphoreFullException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Threading.SynchronizationLockException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Threading.Tasks.TaskCanceledException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Threading.ThreadAbortException", DbgExceptionDefinitionFlags.None),
			new ExceptionInfo("System.Threading.ThreadInterruptedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Threading.ThreadStartException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Threading.ThreadStateException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Threading.WaitHandleCannotBeOpenedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.TimeoutException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.TimeZoneNotFoundException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Transactions.TransactionAbortedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Transactions.TransactionException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Transactions.TransactionInDoubtException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Transactions.TransactionManagerCommunicationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Transactions.TransactionPromotionException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.TypeAccessException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.TypeInitializationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.TypeLoadException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.TypeUnloadedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.UnauthorizedAccessException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.UriFormatException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Web.Caching.DatabaseNotEnabledForNotificationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Web.Caching.TableNotEnabledForNotificationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Web.HttpCompileException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Web.HttpException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Web.HttpParseException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Web.HttpRequestValidationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Web.HttpUnhandledException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Web.Management.SqlExecutionException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Web.Security.MembershipCreateUserException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Web.Security.MembershipPasswordException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Web.Services.Protocols.SoapException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Web.Services.Protocols.SoapHeaderException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Web.UI.ViewStateException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Windows.Automation.ElementNotAvailableException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Windows.Automation.ElementNotEnabledException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Windows.Automation.NoClickablePointException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Windows.Automation.ProxyAssemblyNotLoadedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Windows.Controls.PrintDialogException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Windows.Forms.AxHost+InvalidActiveXStateException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Windows.Markup.XamlParseException", DbgExceptionDefinitionFlags.StopFirstChance | DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Windows.Media.Animation.AnimationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Windows.Media.InvalidWmpVersionException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Windows.ResourceReferenceKeyNotFoundException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Windows.Xps.XpsException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Windows.Xps.XpsPackagingException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Windows.Xps.XpsSerializationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Windows.Xps.XpsWriterException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Workflow.Activities.EventDeliveryFailedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Workflow.Activities.Rules.RuleEvaluationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Workflow.Activities.Rules.RuleEvaluationIncompatibleTypesException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Workflow.Activities.Rules.RuleException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Workflow.Activities.Rules.RuleSetValidationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Workflow.Activities.WorkflowAuthorizationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Workflow.ComponentModel.Compiler.WorkflowValidationFailedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Workflow.ComponentModel.Serialization.WorkflowMarkupSerializationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Workflow.ComponentModel.WorkflowTerminatedException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Workflow.Runtime.Hosting.PersistenceException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Workflow.Runtime.Tracking.TrackingProfileDeserializationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Workflow.Runtime.WorkflowOwnershipException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Xml.Schema.XmlSchemaException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Xml.Schema.XmlSchemaInferenceException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Xml.Schema.XmlSchemaValidationException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Xml.XmlException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Xml.XPath.XPathException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Xml.Xsl.XsltCompileException", DbgExceptionDefinitionFlags.StopSecondChance),
			new ExceptionInfo("System.Xml.Xsl.XsltException", DbgExceptionDefinitionFlags.StopSecondChance),
		};
		const string groupName = PredefinedExceptionGroups.DotNet;
		const string groupDisplayName = "Common Language Runtime Exceptions";

		public override IEnumerable<DbgExceptionGroupDefinition> CreateGroups() {
			yield return new DbgExceptionGroupDefinition(DbgExceptionGroupDefinitionFlags.None, groupName, groupDisplayName);
		}

		public override IEnumerable<DbgExceptionDefinition> Create() {
			foreach (var info in exceptionInfos)
				yield return new DbgExceptionDefinition(new DbgExceptionId(groupName, info.Name), info.Flags);
		}
	}
}
