//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnSpy.BamlDecompiler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class dnSpy_BamlDecompiler_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal dnSpy_BamlDecompiler_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dnSpy.BamlDecompiler.Properties.dnSpy.BamlDecompiler.Resources", typeof(dnSpy_BamlDecompiler_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAML File.
        /// </summary>
        public static string BAMLFile {
            get {
                return ResourceManager.GetString("BAMLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAML.
        /// </summary>
        public static string BamlOptionDlgTab {
            get {
                return ResourceManager.GetString("BamlOptionDlgTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disassemble BAML.
        /// </summary>
        public static string BamlSettings_DisassembleBAML {
            get {
                return ResourceManager.GetString("BamlSettings_DisassembleBAML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disassembles BAML records instead of decompiling it to XAML..
        /// </summary>
        public static string BamlSettings_DisassembleBAML_ToolTip {
            get {
                return ResourceManager.GetString("BamlSettings_DisassembleBAML_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disassemble BAML.
        /// </summary>
        public static string DisassembleBAMLCommand {
            get {
                return ResourceManager.GetString("DisassembleBAMLCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached event &apos;{0}&apos;..
        /// </summary>
        public static string Error_AttachedEvent {
            get {
                return ResourceManager.GetString("Error_AttachedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class &apos;{0}&apos; has IComponentConnector.Connect method, but cannot be parsed..
        /// </summary>
        public static string Error_IComponentConnectorConnetCannotBeParsed {
            get {
                return ResourceManager.GetString("Error_IComponentConnectorConnetCannotBeParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown connection ID: {0}.
        /// </summary>
        public static string Error_UnknownConnectionId {
            get {
                return ResourceManager.GetString("Error_UnknownConnectionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save BAML....
        /// </summary>
        public static string SaveBAML {
            get {
                return ResourceManager.GetString("SaveBAML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save XAML....
        /// </summary>
        public static string SaveXAML {
            get {
                return ResourceManager.GetString("SaveXAML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML File.
        /// </summary>
        public static string XAMLFile {
            get {
                return ResourceManager.GetString("XAMLFile", resourceCulture);
            }
        }
    }
}
