//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnSpy.Analyzer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class dnSpy_Analyzer_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal dnSpy_Analyzer_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dnSpy.Analyzer.Properties.dnSpy.Analyzer.Resources", typeof(dnSpy_Analyzer_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analy_ze.
        /// </summary>
        public static string AnalyzeCommand {
            get {
                return ResourceManager.GetString("AnalyzeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzer.
        /// </summary>
        public static string AnalyzerWindowTitle {
            get {
                return ResourceManager.GetString("AnalyzerWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied To.
        /// </summary>
        public static string AppliedToTreeNode {
            get {
                return ResourceManager.GetString("AppliedToTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned By.
        /// </summary>
        public static string AssignedByTreeNode {
            get {
                return ResourceManager.GetString("AssignedByTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cop_y.
        /// </summary>
        public static string CopyCommand {
            get {
                return ResourceManager.GetString("CopyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dbl Click.
        /// </summary>
        public static string DoubleClick {
            get {
                return ResourceManager.GetString("DoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string EventAdderTreeNodeName {
            get {
                return ResourceManager.GetString("EventAdderTreeNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        public static string EventRemoverTreeNodeName {
            get {
                return ResourceManager.GetString("EventRemoverTreeNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposed By.
        /// </summary>
        public static string ExposedByTreeNode {
            get {
                return ResourceManager.GetString("ExposedByTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Methods.
        /// </summary>
        public static string ExtensionMethodsTreeNode {
            get {
                return ResourceManager.GetString("ExtensionMethodsTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Reference.
        /// </summary>
        public static string GoToReferenceCommand {
            get {
                return ResourceManager.GetString("GoToReferenceCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Reference in Method.
        /// </summary>
        public static string GoToReferenceInCodeCommand {
            get {
                return ResourceManager.GetString("GoToReferenceInCodeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Reference in Method (New _Tab).
        /// </summary>
        public static string GoToReferenceInCodeNewTabCommand {
            get {
                return ResourceManager.GetString("GoToReferenceInCodeNewTabCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Reference (New Ta_b).
        /// </summary>
        public static string GoToReferenceNewTabCommand {
            get {
                return ResourceManager.GetString("GoToReferenceNewTabCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hides.
        /// </summary>
        public static string HidesParent {
            get {
                return ResourceManager.GetString("HidesParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implemented By.
        /// </summary>
        public static string ImplementedByTreeNode {
            get {
                return ResourceManager.GetString("ImplementedByTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instantiated By.
        /// </summary>
        public static string InstantiatedByTreeNode {
            get {
                return ResourceManager.GetString("InstantiatedByTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overridden By.
        /// </summary>
        public static string OverriddenByTreeNode {
            get {
                return ResourceManager.GetString("OverriddenByTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzes assemblies.
        /// </summary>
        public static string Plugin_ShortDescription {
            get {
                return ResourceManager.GetString("Plugin_ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get.
        /// </summary>
        public static string PropertyGetterTreeNode {
            get {
                return ResourceManager.GetString("PropertyGetterTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set.
        /// </summary>
        public static string PropertySetterTreeNode {
            get {
                return ResourceManager.GetString("PropertySetterTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raised By.
        /// </summary>
        public static string RaisedByTreeNode {
            get {
                return ResourceManager.GetString("RaisedByTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read By.
        /// </summary>
        public static string ReadByTreeNode {
            get {
                return ResourceManager.GetString("ReadByTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove.
        /// </summary>
        public static string RemoveCommand {
            get {
                return ResourceManager.GetString("RemoveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift+Dbl Click.
        /// </summary>
        public static string ShiftDoubleClick {
            get {
                return ResourceManager.GetString("ShiftDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+C.
        /// </summary>
        public static string ShortCutKeyCtrlC {
            get {
                return ResourceManager.GetString("ShortCutKeyCtrlC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+R.
        /// </summary>
        public static string ShortCutKeyCtrlR {
            get {
                return ResourceManager.GetString("ShortCutKeyCtrlR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del.
        /// </summary>
        public static string ShortCutKeyDelete {
            get {
                return ResourceManager.GetString("ShortCutKeyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tokens.
        /// </summary>
        public static string ShowMetadataTokensCommand {
            get {
                return ResourceManager.GetString("ShowMetadataTokensCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax Highlight.
        /// </summary>
        public static string SyntaxHighlightCommand {
            get {
                return ResourceManager.GetString("SyntaxHighlightCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used By.
        /// </summary>
        public static string UsedByTreeNode {
            get {
                return ResourceManager.GetString("UsedByTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses.
        /// </summary>
        public static string UsesTreeNode {
            get {
                return ResourceManager.GetString("UsesTreeNode", resourceCulture);
            }
        }
    }
}
