//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnSpy_Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class dnSpy_Console_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal dnSpy_Console_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dnSpy_Console.Properties.dnSpy.Console.Resources", typeof(dnSpy_Console_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} couldn&apos;t be found.
        /// </summary>
        internal static string CouldNotFindTypeX {
            get {
                return ResourceManager.GetString("CouldNotFindTypeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t resolve GAC assembly &apos;{0}&apos;.
        /// </summary>
        internal static string CouldNotResolveGacFileX {
            get {
                return ResourceManager.GetString("CouldNotResolveGacFileX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: {0}.
        /// </summary>
        internal static string Error1 {
            get {
                return ResourceManager.GetString("Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples:
        ///  {0} -o c:\out\path C:\some\path
        ///      Decompiles all .NET files in the above directory and saves files to C:\out\path
        ///  {0} -o c:\out\path -r C:\some\path
        ///      Decompiles all .NET files in the above directory and all sub directories
        ///  {0} -o C:\out\path C:\some\path\*.dll
        ///      Decompiles all *.dll .NET files in the above directory and saves files to C:\out\path
        ///  {0} --md 0x06000123 file.dll
        ///      Decompiles the member with token 0x06000123
        ///  {0} -t system.int32 --gac-file &quot;mscorlib,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Examples {
            get {
                return ResourceManager.GetString("Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File/directory &apos;{0}&apos; doesn&apos;t exist.
        /// </summary>
        internal static string FileOrDirDoesNotExist {
            get {
                return ResourceManager.GetString("FileOrDirDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid integer: &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidInteger {
            get {
                return ResourceManager.GetString("InvalidInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only types, methods, fields, events and properties can be decompiled.
        /// </summary>
        internal static string InvalidMemberToDecompile {
            get {
                return ResourceManager.GetString("InvalidMemberToDecompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid option: {0}.
        /// </summary>
        internal static string InvalidOption {
            get {
                return ResourceManager.GetString("InvalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order argument.
        /// </summary>
        internal static string InvalidOrderArg {
            get {
                return ResourceManager.GetString("InvalidOrderArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .sln name ({0}) must be relative to project directory.
        /// </summary>
        internal static string InvalidSolutionName {
            get {
                return ResourceManager.GetString("InvalidSolutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid metadata token.
        /// </summary>
        internal static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Visual Studio version: {0}.
        /// </summary>
        internal static string InvalidVSVersion {
            get {
                return ResourceManager.GetString("InvalidVSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language &apos;{0}&apos; doesn&apos;t exist.
        /// </summary>
        internal static string LanguageDoesNotExist {
            get {
                return ResourceManager.GetString("LanguageDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages:.
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language {0} does not exist.
        /// </summary>
        internal static string LanguageXDoesNotExist {
            get {
                return ResourceManager.GetString("LanguageXDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language {0} doesn&apos;t support creating project files.
        /// </summary>
        internal static string LanguageXDoesNotSupportProjects {
            get {
                return ResourceManager.GetString("LanguageXDoesNotSupportProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing assembly search path.
        /// </summary>
        internal static string MissingAsmSearchPath {
            get {
                return ResourceManager.GetString("MissingAsmSearchPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing .NET filename.
        /// </summary>
        internal static string MissingDotNetFilename {
            get {
                return ResourceManager.GetString("MissingDotNetFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing GAC assembly name.
        /// </summary>
        internal static string MissingGacFile {
            get {
                return ResourceManager.GetString("MissingGacFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing language name.
        /// </summary>
        internal static string MissingLanguageName {
            get {
                return ResourceManager.GetString("MissingLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing metadata token.
        /// </summary>
        internal static string MissingMDToken {
            get {
                return ResourceManager.GetString("MissingMDToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing number of threads.
        /// </summary>
        internal static string MissingNumberOfThreads {
            get {
                return ResourceManager.GetString("MissingNumberOfThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No options specified.
        /// </summary>
        internal static string MissingOptions {
            get {
                return ResourceManager.GetString("MissingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing order argument.
        /// </summary>
        internal static string MissingOrderArg {
            get {
                return ResourceManager.GetString("MissingOrderArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing output directory.
        /// </summary>
        internal static string MissingOutputDir {
            get {
                return ResourceManager.GetString("MissingOutputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing .sln name.
        /// </summary>
        internal static string MissingSolutionName {
            get {
                return ResourceManager.GetString("MissingSolutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing full name of type.
        /// </summary>
        internal static string MissingTypeName {
            get {
                return ResourceManager.GetString("MissingTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing user GAC path.
        /// </summary>
        internal static string MissingUserGacPath {
            get {
                return ResourceManager.GetString("MissingUserGacPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Visual Studio version.
        /// </summary>
        internal static string MissingVSVersion {
            get {
                return ResourceManager.GetString("MissingVSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No languages were found. Make sure that the language dll files exist in the same folder as this program..
        /// </summary>
        internal static string NoLanguagesFound {
            get {
                return ResourceManager.GetString("NoLanguagesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a .NET file.
        /// </summary>
        internal static string NotDotNetFile {
            get {
                return ResourceManager.GetString("NotDotNetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one file can be decompiled when using --md.
        /// </summary>
        internal static string OnlyOneFileCanBeDecompiled {
            get {
                return ResourceManager.GetString("OnlyOneFileCanBeDecompiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [options] [fileOrDir1] [fileOrDir2] [...]
        ///  --asm-path path    assembly search path. Paths can be separated with &apos;{1}&apos; or you can use multiple --asm-path&apos;s
        ///  --user-gac path    user GAC path. Paths can be separated with &apos;{1}&apos; or you can use multiple --user-gac&apos;s
        ///  --no-gac     don&apos;t use the GAC to look up assemblies. Useful with --no-stdlib
        ///  --no-stdlib  projects don&apos;t reference mscorlib
        ///  --no-sln     don&apos;t create a .sln file
        ///  --no-xmldoc  don&apos;t show XML doc comments
        ///  --il-comments show IL co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
    }
}
