//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSharpCode.NRefactory.VB.Visitors {
	using System;
	using ICSharpCode.NRefactory.VB.Dom;
	
	
	/// <summary>
	/// IDomVisitor implementation that always throws NotImplementedExceptions.
	/// </summary>
	public class NotImplementedDomVisitor : IDomVisitor {
		
		public virtual object VisitAddHandlerStatement(AddHandlerStatement addHandlerStatement, object data) {
			throw new global::System.NotImplementedException("AddHandlerStatement");
		}
		
		public virtual object VisitAddressOfExpression(AddressOfExpression addressOfExpression, object data) {
			throw new global::System.NotImplementedException("AddressOfExpression");
		}
		
		public virtual object VisitArrayCreateExpression(ArrayCreateExpression arrayCreateExpression, object data) {
			throw new global::System.NotImplementedException("ArrayCreateExpression");
		}
		
		public virtual object VisitAssignmentExpression(AssignmentExpression assignmentExpression, object data) {
			throw new global::System.NotImplementedException("AssignmentExpression");
		}
		
		public virtual object VisitAttribute(ICSharpCode.NRefactory.VB.Dom.Attribute attribute, object data) {
			throw new global::System.NotImplementedException("Attribute");
		}
		
		public virtual object VisitAttributeSection(AttributeSection attributeSection, object data) {
			throw new global::System.NotImplementedException("AttributeSection");
		}
		
		public virtual object VisitBaseReferenceExpression(BaseReferenceExpression baseReferenceExpression, object data) {
			throw new global::System.NotImplementedException("BaseReferenceExpression");
		}
		
		public virtual object VisitBinaryOperatorExpression(BinaryOperatorExpression binaryOperatorExpression, object data) {
			throw new global::System.NotImplementedException("BinaryOperatorExpression");
		}
		
		public virtual object VisitBlockStatement(BlockStatement blockStatement, object data) {
			throw new global::System.NotImplementedException("BlockStatement");
		}
		
		public virtual object VisitCaseLabel(CaseLabel caseLabel, object data) {
			throw new global::System.NotImplementedException("CaseLabel");
		}
		
		public virtual object VisitCastExpression(CastExpression castExpression, object data) {
			throw new global::System.NotImplementedException("CastExpression");
		}
		
		public virtual object VisitCatchClause(CatchClause catchClause, object data) {
			throw new global::System.NotImplementedException("CatchClause");
		}
		
		public virtual object VisitClassReferenceExpression(ClassReferenceExpression classReferenceExpression, object data) {
			throw new global::System.NotImplementedException("ClassReferenceExpression");
		}
		
		public virtual object VisitCollectionInitializerExpression(CollectionInitializerExpression collectionInitializerExpression, object data) {
			throw new global::System.NotImplementedException("CollectionInitializerExpression");
		}
		
		public virtual object VisitCollectionRangeVariable(CollectionRangeVariable collectionRangeVariable, object data) {
			throw new global::System.NotImplementedException("CollectionRangeVariable");
		}
		
		public virtual object VisitCompilationUnit(CompilationUnit compilationUnit, object data) {
			throw new global::System.NotImplementedException("CompilationUnit");
		}
		
		public virtual object VisitConditionalExpression(ConditionalExpression conditionalExpression, object data) {
			throw new global::System.NotImplementedException("ConditionalExpression");
		}
		
		public virtual object VisitConstructorDeclaration(ConstructorDeclaration constructorDeclaration, object data) {
			throw new global::System.NotImplementedException("ConstructorDeclaration");
		}
		
		public virtual object VisitConstructorInitializer(ConstructorInitializer constructorInitializer, object data) {
			throw new global::System.NotImplementedException("ConstructorInitializer");
		}
		
		public virtual object VisitContinueStatement(ContinueStatement continueStatement, object data) {
			throw new global::System.NotImplementedException("ContinueStatement");
		}
		
		public virtual object VisitDeclareDeclaration(DeclareDeclaration declareDeclaration, object data) {
			throw new global::System.NotImplementedException("DeclareDeclaration");
		}
		
		public virtual object VisitDefaultValueExpression(DefaultValueExpression defaultValueExpression, object data) {
			throw new global::System.NotImplementedException("DefaultValueExpression");
		}
		
		public virtual object VisitDelegateDeclaration(DelegateDeclaration delegateDeclaration, object data) {
			throw new global::System.NotImplementedException("DelegateDeclaration");
		}
		
		public virtual object VisitDirectionExpression(DirectionExpression directionExpression, object data) {
			throw new global::System.NotImplementedException("DirectionExpression");
		}
		
		public virtual object VisitDoLoopStatement(DoLoopStatement doLoopStatement, object data) {
			throw new global::System.NotImplementedException("DoLoopStatement");
		}
		
		public virtual object VisitElseIfSection(ElseIfSection elseIfSection, object data) {
			throw new global::System.NotImplementedException("ElseIfSection");
		}
		
		public virtual object VisitEndStatement(EndStatement endStatement, object data) {
			throw new global::System.NotImplementedException("EndStatement");
		}
		
		public virtual object VisitEraseStatement(EraseStatement eraseStatement, object data) {
			throw new global::System.NotImplementedException("EraseStatement");
		}
		
		public virtual object VisitErrorStatement(ErrorStatement errorStatement, object data) {
			throw new global::System.NotImplementedException("ErrorStatement");
		}
		
		public virtual object VisitEventAddRegion(EventAddRegion eventAddRegion, object data) {
			throw new global::System.NotImplementedException("EventAddRegion");
		}
		
		public virtual object VisitEventDeclaration(EventDeclaration eventDeclaration, object data) {
			throw new global::System.NotImplementedException("EventDeclaration");
		}
		
		public virtual object VisitEventRaiseRegion(EventRaiseRegion eventRaiseRegion, object data) {
			throw new global::System.NotImplementedException("EventRaiseRegion");
		}
		
		public virtual object VisitEventRemoveRegion(EventRemoveRegion eventRemoveRegion, object data) {
			throw new global::System.NotImplementedException("EventRemoveRegion");
		}
		
		public virtual object VisitExitStatement(ExitStatement exitStatement, object data) {
			throw new global::System.NotImplementedException("ExitStatement");
		}
		
		public virtual object VisitExpressionRangeVariable(ExpressionRangeVariable expressionRangeVariable, object data) {
			throw new global::System.NotImplementedException("ExpressionRangeVariable");
		}
		
		public virtual object VisitExpressionStatement(ExpressionStatement expressionStatement, object data) {
			throw new global::System.NotImplementedException("ExpressionStatement");
		}
		
		public virtual object VisitExternAliasDirective(ExternAliasDirective externAliasDirective, object data) {
			throw new global::System.NotImplementedException("ExternAliasDirective");
		}
		
		public virtual object VisitFieldDeclaration(FieldDeclaration fieldDeclaration, object data) {
			throw new global::System.NotImplementedException("FieldDeclaration");
		}
		
		public virtual object VisitForeachStatement(ForeachStatement foreachStatement, object data) {
			throw new global::System.NotImplementedException("ForeachStatement");
		}
		
		public virtual object VisitForNextStatement(ForNextStatement forNextStatement, object data) {
			throw new global::System.NotImplementedException("ForNextStatement");
		}
		
		public virtual object VisitGotoStatement(GotoStatement gotoStatement, object data) {
			throw new global::System.NotImplementedException("GotoStatement");
		}
		
		public virtual object VisitIdentifierExpression(IdentifierExpression identifierExpression, object data) {
			throw new global::System.NotImplementedException("IdentifierExpression");
		}
		
		public virtual object VisitIfElseStatement(IfElseStatement ifElseStatement, object data) {
			throw new global::System.NotImplementedException("IfElseStatement");
		}
		
		public virtual object VisitInnerClassTypeReference(InnerClassTypeReference innerClassTypeReference, object data) {
			throw new global::System.NotImplementedException("InnerClassTypeReference");
		}
		
		public virtual object VisitInterfaceImplementation(InterfaceImplementation interfaceImplementation, object data) {
			throw new global::System.NotImplementedException("InterfaceImplementation");
		}
		
		public virtual object VisitInvocationExpression(InvocationExpression invocationExpression, object data) {
			throw new global::System.NotImplementedException("InvocationExpression");
		}
		
		public virtual object VisitLabelStatement(LabelStatement labelStatement, object data) {
			throw new global::System.NotImplementedException("LabelStatement");
		}
		
		public virtual object VisitLambdaExpression(LambdaExpression lambdaExpression, object data) {
			throw new global::System.NotImplementedException("LambdaExpression");
		}
		
		public virtual object VisitLocalVariableDeclaration(LocalVariableDeclaration localVariableDeclaration, object data) {
			throw new global::System.NotImplementedException("LocalVariableDeclaration");
		}
		
		public virtual object VisitLockStatement(LockStatement lockStatement, object data) {
			throw new global::System.NotImplementedException("LockStatement");
		}
		
		public virtual object VisitMemberInitializerExpression(MemberInitializerExpression memberInitializerExpression, object data) {
			throw new global::System.NotImplementedException("MemberInitializerExpression");
		}
		
		public virtual object VisitMemberReferenceExpression(MemberReferenceExpression memberReferenceExpression, object data) {
			throw new global::System.NotImplementedException("MemberReferenceExpression");
		}
		
		public virtual object VisitMethodDeclaration(MethodDeclaration methodDeclaration, object data) {
			throw new global::System.NotImplementedException("MethodDeclaration");
		}
		
		public virtual object VisitNamedArgumentExpression(NamedArgumentExpression namedArgumentExpression, object data) {
			throw new global::System.NotImplementedException("NamedArgumentExpression");
		}
		
		public virtual object VisitNamespaceDeclaration(NamespaceDeclaration namespaceDeclaration, object data) {
			throw new global::System.NotImplementedException("NamespaceDeclaration");
		}
		
		public virtual object VisitObjectCreateExpression(ObjectCreateExpression objectCreateExpression, object data) {
			throw new global::System.NotImplementedException("ObjectCreateExpression");
		}
		
		public virtual object VisitOnErrorStatement(OnErrorStatement onErrorStatement, object data) {
			throw new global::System.NotImplementedException("OnErrorStatement");
		}
		
		public virtual object VisitOperatorDeclaration(OperatorDeclaration operatorDeclaration, object data) {
			throw new global::System.NotImplementedException("OperatorDeclaration");
		}
		
		public virtual object VisitOptionDeclaration(OptionDeclaration optionDeclaration, object data) {
			throw new global::System.NotImplementedException("OptionDeclaration");
		}
		
		public virtual object VisitParameterDeclarationExpression(ParameterDeclarationExpression parameterDeclarationExpression, object data) {
			throw new global::System.NotImplementedException("ParameterDeclarationExpression");
		}
		
		public virtual object VisitParenthesizedExpression(ParenthesizedExpression parenthesizedExpression, object data) {
			throw new global::System.NotImplementedException("ParenthesizedExpression");
		}
		
		public virtual object VisitPrimitiveExpression(PrimitiveExpression primitiveExpression, object data) {
			throw new global::System.NotImplementedException("PrimitiveExpression");
		}
		
		public virtual object VisitPropertyDeclaration(PropertyDeclaration propertyDeclaration, object data) {
			throw new global::System.NotImplementedException("PropertyDeclaration");
		}
		
		public virtual object VisitPropertyGetRegion(PropertyGetRegion propertyGetRegion, object data) {
			throw new global::System.NotImplementedException("PropertyGetRegion");
		}
		
		public virtual object VisitPropertySetRegion(PropertySetRegion propertySetRegion, object data) {
			throw new global::System.NotImplementedException("PropertySetRegion");
		}
		
		public virtual object VisitQueryExpression(QueryExpression queryExpression, object data) {
			throw new global::System.NotImplementedException("QueryExpression");
		}
		
		public virtual object VisitQueryExpressionAggregateClause(QueryExpressionAggregateClause queryExpressionAggregateClause, object data) {
			throw new global::System.NotImplementedException("QueryExpressionAggregateClause");
		}
		
		public virtual object VisitQueryExpressionDistinctClause(QueryExpressionDistinctClause queryExpressionDistinctClause, object data) {
			throw new global::System.NotImplementedException("QueryExpressionDistinctClause");
		}
		
		public virtual object VisitQueryExpressionFromClause(QueryExpressionFromClause queryExpressionFromClause, object data) {
			throw new global::System.NotImplementedException("QueryExpressionFromClause");
		}
		
		public virtual object VisitQueryExpressionGroupClause(QueryExpressionGroupClause queryExpressionGroupClause, object data) {
			throw new global::System.NotImplementedException("QueryExpressionGroupClause");
		}
		
		public virtual object VisitQueryExpressionGroupJoinVBClause(QueryExpressionGroupJoinVBClause queryExpressionGroupJoinVBClause, object data) {
			throw new global::System.NotImplementedException("QueryExpressionGroupJoinVBClause");
		}
		
		public virtual object VisitQueryExpressionGroupVBClause(QueryExpressionGroupVBClause queryExpressionGroupVBClause, object data) {
			throw new global::System.NotImplementedException("QueryExpressionGroupVBClause");
		}
		
		public virtual object VisitQueryExpressionJoinClause(QueryExpressionJoinClause queryExpressionJoinClause, object data) {
			throw new global::System.NotImplementedException("QueryExpressionJoinClause");
		}
		
		public virtual object VisitQueryExpressionJoinConditionVB(QueryExpressionJoinConditionVB queryExpressionJoinConditionVB, object data) {
			throw new global::System.NotImplementedException("QueryExpressionJoinConditionVB");
		}
		
		public virtual object VisitQueryExpressionJoinVBClause(QueryExpressionJoinVBClause queryExpressionJoinVBClause, object data) {
			throw new global::System.NotImplementedException("QueryExpressionJoinVBClause");
		}
		
		public virtual object VisitQueryExpressionLetClause(QueryExpressionLetClause queryExpressionLetClause, object data) {
			throw new global::System.NotImplementedException("QueryExpressionLetClause");
		}
		
		public virtual object VisitQueryExpressionLetVBClause(QueryExpressionLetVBClause queryExpressionLetVBClause, object data) {
			throw new global::System.NotImplementedException("QueryExpressionLetVBClause");
		}
		
		public virtual object VisitQueryExpressionOrderClause(QueryExpressionOrderClause queryExpressionOrderClause, object data) {
			throw new global::System.NotImplementedException("QueryExpressionOrderClause");
		}
		
		public virtual object VisitQueryExpressionOrdering(QueryExpressionOrdering queryExpressionOrdering, object data) {
			throw new global::System.NotImplementedException("QueryExpressionOrdering");
		}
		
		public virtual object VisitQueryExpressionPartitionVBClause(QueryExpressionPartitionVBClause queryExpressionPartitionVBClause, object data) {
			throw new global::System.NotImplementedException("QueryExpressionPartitionVBClause");
		}
		
		public virtual object VisitQueryExpressionSelectClause(QueryExpressionSelectClause queryExpressionSelectClause, object data) {
			throw new global::System.NotImplementedException("QueryExpressionSelectClause");
		}
		
		public virtual object VisitQueryExpressionSelectVBClause(QueryExpressionSelectVBClause queryExpressionSelectVBClause, object data) {
			throw new global::System.NotImplementedException("QueryExpressionSelectVBClause");
		}
		
		public virtual object VisitQueryExpressionWhereClause(QueryExpressionWhereClause queryExpressionWhereClause, object data) {
			throw new global::System.NotImplementedException("QueryExpressionWhereClause");
		}
		
		public virtual object VisitRaiseEventStatement(RaiseEventStatement raiseEventStatement, object data) {
			throw new global::System.NotImplementedException("RaiseEventStatement");
		}
		
		public virtual object VisitReDimStatement(ReDimStatement reDimStatement, object data) {
			throw new global::System.NotImplementedException("ReDimStatement");
		}
		
		public virtual object VisitRemoveHandlerStatement(RemoveHandlerStatement removeHandlerStatement, object data) {
			throw new global::System.NotImplementedException("RemoveHandlerStatement");
		}
		
		public virtual object VisitResumeStatement(ResumeStatement resumeStatement, object data) {
			throw new global::System.NotImplementedException("ResumeStatement");
		}
		
		public virtual object VisitReturnStatement(ReturnStatement returnStatement, object data) {
			throw new global::System.NotImplementedException("ReturnStatement");
		}
		
		public virtual object VisitStopStatement(StopStatement stopStatement, object data) {
			throw new global::System.NotImplementedException("StopStatement");
		}
		
		public virtual object VisitSwitchSection(SwitchSection switchSection, object data) {
			throw new global::System.NotImplementedException("SwitchSection");
		}
		
		public virtual object VisitSwitchStatement(SwitchStatement switchStatement, object data) {
			throw new global::System.NotImplementedException("SwitchStatement");
		}
		
		public virtual object VisitTemplateDefinition(TemplateDefinition templateDefinition, object data) {
			throw new global::System.NotImplementedException("TemplateDefinition");
		}
		
		public virtual object VisitThisReferenceExpression(ThisReferenceExpression thisReferenceExpression, object data) {
			throw new global::System.NotImplementedException("ThisReferenceExpression");
		}
		
		public virtual object VisitThrowStatement(ThrowStatement throwStatement, object data) {
			throw new global::System.NotImplementedException("ThrowStatement");
		}
		
		public virtual object VisitTryCatchStatement(TryCatchStatement tryCatchStatement, object data) {
			throw new global::System.NotImplementedException("TryCatchStatement");
		}
		
		public virtual object VisitTypeDeclaration(TypeDeclaration typeDeclaration, object data) {
			throw new global::System.NotImplementedException("TypeDeclaration");
		}
		
		public virtual object VisitTypeOfExpression(TypeOfExpression typeOfExpression, object data) {
			throw new global::System.NotImplementedException("TypeOfExpression");
		}
		
		public virtual object VisitTypeOfIsExpression(TypeOfIsExpression typeOfIsExpression, object data) {
			throw new global::System.NotImplementedException("TypeOfIsExpression");
		}
		
		public virtual object VisitTypeReference(TypeReference typeReference, object data) {
			throw new global::System.NotImplementedException("TypeReference");
		}
		
		public virtual object VisitTypeReferenceExpression(TypeReferenceExpression typeReferenceExpression, object data) {
			throw new global::System.NotImplementedException("TypeReferenceExpression");
		}
		
		public virtual object VisitUnaryOperatorExpression(UnaryOperatorExpression unaryOperatorExpression, object data) {
			throw new global::System.NotImplementedException("UnaryOperatorExpression");
		}
		
		public virtual object VisitUsing(Using @using, object data) {
			throw new global::System.NotImplementedException("Using");
		}
		
		public virtual object VisitUsingDeclaration(UsingDeclaration usingDeclaration, object data) {
			throw new global::System.NotImplementedException("UsingDeclaration");
		}
		
		public virtual object VisitUsingStatement(UsingStatement usingStatement, object data) {
			throw new global::System.NotImplementedException("UsingStatement");
		}
		
		public virtual object VisitVariableDeclaration(VariableDeclaration variableDeclaration, object data) {
			throw new global::System.NotImplementedException("VariableDeclaration");
		}
		
		public virtual object VisitWithStatement(WithStatement withStatement, object data) {
			throw new global::System.NotImplementedException("WithStatement");
		}
		
		public virtual object VisitXmlAttributeExpression(XmlAttributeExpression xmlAttributeExpression, object data) {
			throw new global::System.NotImplementedException("XmlAttributeExpression");
		}
		
		public virtual object VisitXmlContentExpression(XmlContentExpression xmlContentExpression, object data) {
			throw new global::System.NotImplementedException("XmlContentExpression");
		}
		
		public virtual object VisitXmlDocumentExpression(XmlDocumentExpression xmlDocumentExpression, object data) {
			throw new global::System.NotImplementedException("XmlDocumentExpression");
		}
		
		public virtual object VisitXmlElementExpression(XmlElementExpression xmlElementExpression, object data) {
			throw new global::System.NotImplementedException("XmlElementExpression");
		}
		
		public virtual object VisitXmlEmbeddedExpression(XmlEmbeddedExpression xmlEmbeddedExpression, object data) {
			throw new global::System.NotImplementedException("XmlEmbeddedExpression");
		}
		
		public virtual object VisitXmlMemberAccessExpression(XmlMemberAccessExpression xmlMemberAccessExpression, object data) {
			throw new global::System.NotImplementedException("XmlMemberAccessExpression");
		}
	}
}
