//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnSpy.Roslyn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class dnSpy_Roslyn_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal dnSpy_Roslyn_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dnSpy.Roslyn.Properties.dnSpy.Roslyn.Resources", typeof(dnSpy_Roslyn_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string ClassesToolTip {
            get {
                return ResourceManager.GetString("ClassesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow unsafe code.
        /// </summary>
        public static string CompilerSettings_AllowUnsafe {
            get {
                return ResourceManager.GetString("CompilerSettings_AllowUnsafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for arithmetic overflow/underflow.
        /// </summary>
        public static string CompilerSettings_CheckOverflow {
            get {
                return ResourceManager.GetString("CompilerSettings_CheckOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed Visual Basic runtime.
        /// </summary>
        public static string CompilerSettings_EmbedVBRuntime {
            get {
                return ResourceManager.GetString("CompilerSettings_EmbedVBRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize code.
        /// </summary>
        public static string CompilerSettings_Optimize {
            get {
                return ResourceManager.GetString("CompilerSettings_Optimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option compare: binary.
        /// </summary>
        public static string CompilerSettings_OptionCompareBinary {
            get {
                return ResourceManager.GetString("CompilerSettings_OptionCompareBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option explicit.
        /// </summary>
        public static string CompilerSettings_OptionExplicit {
            get {
                return ResourceManager.GetString("CompilerSettings_OptionExplicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option infer.
        /// </summary>
        public static string CompilerSettings_OptionInfer {
            get {
                return ResourceManager.GetString("CompilerSettings_OptionInfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option strict.
        /// </summary>
        public static string CompilerSettings_OptionStrict {
            get {
                return ResourceManager.GetString("CompilerSettings_OptionStrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional compilation symbols.
        /// </summary>
        public static string CompilerSettings_PreprocessorSymbols {
            get {
                return ResourceManager.GetString("CompilerSettings_PreprocessorSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string CompletionSet_All {
            get {
                return ResourceManager.GetString("CompletionSet_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constants.
        /// </summary>
        public static string ConstantsToolTip {
            get {
                return ResourceManager.GetString("ConstantsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression has been evaluated and has no value.
        /// </summary>
        public static string DebuggerExpressionHasNoValue {
            get {
                return ResourceManager.GetString("DebuggerExpressionHasNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static members.
        /// </summary>
        public static string DebuggerVarsWindow_CSharp_StaticMembers {
            get {
                return ResourceManager.GetString("DebuggerVarsWindow_CSharp_StaticMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic View.
        /// </summary>
        public static string DebuggerVarsWindow_DynamicView {
            get {
                return ResourceManager.GetString("DebuggerVarsWindow_DynamicView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DebuggerVarsWindow_Error_PropertyName {
            get {
                return ResourceManager.GetString("DebuggerVarsWindow_Error_PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanding the Dynamic View will get the dynamic members for the object.
        /// </summary>
        public static string DebuggerVarsWindow_ExpandDynamicViewMessage {
            get {
                return ResourceManager.GetString("DebuggerVarsWindow_ExpandDynamicViewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanding the Results View will enumerate the IEnumerable.
        /// </summary>
        public static string DebuggerVarsWindow_ExpandResultsViewMessage {
            get {
                return ResourceManager.GetString("DebuggerVarsWindow_ExpandResultsViewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance members.
        /// </summary>
        public static string DebuggerVarsWindow_InstanceMembers {
            get {
                return ResourceManager.GetString("DebuggerVarsWindow_InstanceMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw View.
        /// </summary>
        public static string DebuggerVarsWindow_RawView {
            get {
                return ResourceManager.GetString("DebuggerVarsWindow_RawView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results View.
        /// </summary>
        public static string DebuggerVarsWindow_ResultsView {
            get {
                return ResourceManager.GetString("DebuggerVarsWindow_ResultsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared members.
        /// </summary>
        public static string DebuggerVarsWindow_VisualBasic_SharedMembers {
            get {
                return ResourceManager.GetString("DebuggerVarsWindow_VisualBasic_SharedMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegates.
        /// </summary>
        public static string DelegatesToolTip {
            get {
                return ResourceManager.GetString("DelegatesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only COM or Dynamic objects can have Dynamic View.
        /// </summary>
        public static string DynamicView_MustBeDynamicOrComType {
            get {
                return ResourceManager.GetString("DynamicView_MustBeDynamicOrComType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic View requires {0} to be referenced.
        /// </summary>
        public static string DynamicViewAssemblyNotLoaded {
            get {
                return ResourceManager.GetString("DynamicViewAssemblyNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enums.
        /// </summary>
        public static string EnumsToolTip {
            get {
                return ResourceManager.GetString("EnumsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string EventsToolTip {
            get {
                return ResourceManager.GetString("EventsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension methods.
        /// </summary>
        public static string ExtensionMethodsToolTip {
            get {
                return ResourceManager.GetString("ExtensionMethodsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        public static string FieldsToolTip {
            get {
                return ResourceManager.GetString("FieldsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiled expression threw an exception: {0}.
        /// </summary>
        public static string FilterExpressionEvaluator_CompiledExpressionThrewAnException {
            get {
                return ResourceManager.GetString("FilterExpressionEvaluator_CompiledExpressionThrewAnException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression is invalid.
        /// </summary>
        public static string FilterExpressionEvaluator_InvalidExpression {
            get {
                return ResourceManager.GetString("FilterExpressionEvaluator_InvalidExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interfaces.
        /// </summary>
        public static string InterfacesToolTip {
            get {
                return ResourceManager.GetString("InterfacesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string KeywordsToolTip {
            get {
                return ResourceManager.GetString("KeywordsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locals and parameters.
        /// </summary>
        public static string LocalsAndParametersToolTip {
            get {
                return ResourceManager.GetString("LocalsAndParametersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} returned.
        /// </summary>
        public static string LocalsWindow_MethodOrProperty_Returned {
            get {
                return ResourceManager.GetString("LocalsWindow_MethodOrProperty_Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type variables.
        /// </summary>
        public static string LocalsWindow_TypeVariables {
            get {
                return ResourceManager.GetString("LocalsWindow_TypeVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods.
        /// </summary>
        public static string MethodsToolTip {
            get {
                return ResourceManager.GetString("MethodsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string ModulesToolTip {
            get {
                return ResourceManager.GetString("ModulesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespaces.
        /// </summary>
        public static string NamespacesToolTip {
            get {
                return ResourceManager.GetString("NamespacesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string PropertiesToolTip {
            get {
                return ResourceManager.GetString("PropertiesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Enumerable types can have Results View.
        /// </summary>
        public static string ResultsView_MustBeEnumerableType {
            get {
                return ResourceManager.GetString("ResultsView_MustBeEnumerableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippets.
        /// </summary>
        public static string SnippetsToolTip {
            get {
                return ResourceManager.GetString("SnippetsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structures.
        /// </summary>
        public static string StructuresToolTip {
            get {
                return ResourceManager.GetString("StructuresToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results View requires {0} to be referenced.
        /// </summary>
        public static string SystemCoreDllNotLoaded {
            get {
                return ResourceManager.GetString("SystemCoreDllNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; doesn&apos;t exist in assembly &apos;{1}&apos;.
        /// </summary>
        public static string TypeDoesNotExistInAssembly {
            get {
                return ResourceManager.GetString("TypeDoesNotExistInAssembly", resourceCulture);
            }
        }
    }
}
