//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnSpy.Contracts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class dnSpy_Contracts_DnSpy_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal dnSpy_Contracts_DnSpy_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dnSpy.Contracts.Properties.dnSpy.Contracts.DnSpy.Resources", typeof(dnSpy_Contracts_DnSpy_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred:
        ///
        ///{0}.
        /// </summary>
        public static string AnErrorOccurred {
            get {
                return ResourceManager.GetString("AnErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert &apos;{0}&apos;.
        /// </summary>
        public static string CouldNotConvert {
            get {
                return ResourceManager.GetString("CouldNotConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert it from a string: {0}.
        /// </summary>
        public static string CouldNotConvertFromString {
            get {
                return ResourceManager.GetString("CouldNotConvertFromString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialize data: {0}.
        /// </summary>
        public static string CouldNotDeserializeData {
            get {
                return ResourceManager.GetString("CouldNotDeserializeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Executables.
        /// </summary>
        public static string Files_DotNetExecutables {
            get {
                return ResourceManager.GetString("Files_DotNetExecutables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET NetModules.
        /// </summary>
        public static string Files_DotNetNetModules {
            get {
                return ResourceManager.GetString("Files_DotNetNetModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executables.
        /// </summary>
        public static string Files_Executables {
            get {
                return ResourceManager.GetString("Files_Executables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Files_Images {
            get {
                return ResourceManager.GetString("Files_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong Name Key Files.
        /// </summary>
        public static string Files_StrongNameKeyFiles {
            get {
                return ResourceManager.GetString("Files_StrongNameKeyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid GUID.
        /// </summary>
        public static string InvalidGuid {
            get {
                return ResourceManager.GetString("InvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new data is not an image list..
        /// </summary>
        public static string NewDataNotImageList {
            get {
                return ResourceManager.GetString("NewDataNotImageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not have a TypeConverter and can&apos;t be converted from a string..
        /// </summary>
        public static string NoTypeConverter {
            get {
                return ResourceManager.GetString("NoTypeConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bytes.
        /// </summary>
        public static string NumberOfBytes {
            get {
                return ResourceManager.GetString("NumberOfBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bytes, Type = {1}.
        /// </summary>
        public static string NumberOfBytesAndType {
            get {
                return ResourceManager.GetString("NumberOfBytesAndType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource type can&apos;t be changed.
        /// </summary>
        public static string ResourceTypeCantBeChanged {
            get {
                return ResourceManager.GetString("ResourceTypeCantBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Resource.
        /// </summary>
        public static string SaveResource {
            get {
                return ResourceManager.GetString("SaveResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Resources.
        /// </summary>
        public static string SaveResources {
            get {
                return ResourceManager.GetString("SaveResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be type {0}.
        ///Error: {1}.
        /// </summary>
        public static string ValueMustBeType {
            get {
                return ResourceManager.GetString("ValueMustBeType", resourceCulture);
            }
        }
    }
}
